### PR TITLE
Desktop version 1

### PR DESCRIPTION
**Pull request by Trictonicmp**
## Desktop version 1
In this PR we:
* Added keep-reading-button to the headline section
* Changed nav bar from being a simple bloc to be static always on top
* Added a max-width constraint to cards containers to support wide screens
* Add media queries to support desktop resolutions

### CODE REVIEW

**Review by sja-thedude — CHANGES_REQUESTED** [review]
## Required Changes ♻️

Hi @Trictonicmp, This is @sja-thedude your code reviewer.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

768070f3-bc9a-4aba-b8bc-25793e00ea1e_text

## Highlights
✔️ Great job on working on the project
✔️ Good PR description and title

## Required 
- [x] Kindly fix the conflicts on the pull request which will then show the linters. (Without linters we are not allowed to review but some GitHub action error is going on in GitHub so I am reviewing this. Make sure from next time that linters should pass successfully.)
- [x] Update the readme file with the description of this project.
- [x]  Make sure to use grid for the desktop version.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@sja-thedude] in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Trictonicmp** [comment]
Hi @sja-thedude Thank you for your feedback, I don't know how to resolve GitHub conflicts, I'll do some research about it.
I have a question, Do I have to use Grid to wrap all my sections? because I used grid to wrap "my works" cards and "Skills" cards but I don't know If I'm supposed to use grid to wrap all my sections for the desktop version.

**Review by akucintavalent — APPROVED** [review]
# Approved 👏 

Hi there, @Trictonicmp 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

To Highlight: 
- The Pull Request has a proper title and description. ✔️ 
- You have added a descriptive Readme file. Good Job. ✔️ 
- There is no linter error at present. ✔️ 
- Project has met all the technical aspects you needed for this project. Keep rocking! ✔️ 

[OPTIONAL] REQUIRED CHANGES
- [ ] [OPTIONAL] The border highlighting the form input fields should be green(ish):
image

Figma design:
image
- [ ] [OPTIONAL] At the end of the page there should be large white space and a black line.
Your design:
image

Figma design:
image

- [ ] [OPTIONAL] Kindly update the README file to contain detailed instructions on how to open this page on a local PC

image


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of code reviews per project which you can see from your dashboard. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)_

**Comment by Trictonicmp** [comment]
Hi @akucintavalent Thank you for your feedback!!
the highlight color I tried to do it but somehow seems that the browser keeps overriding it to the default behavior. I'll add those changes in my future PR.

**Pull request merged**
